name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        env:
          sec: ${{ secrets.TEST_PRIVATE }}
        run: |
          echo "sec: $sec"
          echo "secrets.HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}"
          echo "secrets.HELLO: ${{ secrets.HELLO }}"
          echo "secrets.TEST_PRIVATE ${{ secrets.TEST_PRIVATE }}"
          echo "pwd: $(pwd)"
