name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: |
          echo "secrets: ${{ secrets }}"
          echo "secrets.TEST: ${{ secrets.TEST }}"
          echo "secrets.testENV: ${{ secrets.testENV }}"
          echo "secrets.TEST_PRIVATE ${{ secrets.TEST_PRIVATE }}"
          echo "env.TEST: ${{ env.TEST }}"
          echo "env.testENV: ${{ env.testENV }}"
          echo "env.TEST_PRIVATE ${{ env.TEST_PRIVATE }}"
          echo "env.NODE_VERSION: ${{ env.NODE_VERSION }}"
          echo "pwd: $(pwd)"
