name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        env:
          REPO_TEST: ${{ secrets.REPO_TEST }}
        run: |
          if [[ "$REPO_TEST" == "***" ]]; then
            echo "is ***"
          fi
          if [[ "$REPO_TEST" == "HELLO" ]]; then
            echo "is HELLO"
          fi
          echo "REPO_TEST: $REPO_TEST"
          echo "secrets.ENV_TEST: ${{ secrets.ENV_TEST }}"
          echo "secrets.ORG_TEST: ${{ secrets.ORG_TEST }}"
          echo "secrets.REPO_TEST: ${{ secrets.REPO_TEST }}"

          echo "pwd: $(pwd)"
