name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run: |
          echo "secrets: ${{ secrets }}"
          echo "env.TEST ${{ env.TEST }}"
          echo "env.NODE_VERSION: ${{ env.NODE_VERSION }}"
          echo "pwd: $(pwd)"
